create table baiviet
(
    ma_bviet int auto_increment
        primary key,
    tieude   varchar(200) charset utf8          not null,
    ten_bhat varchar(100) charset utf8          not null,
    tomtat   text                               not null,
    noidung  text                               null,
    ngayviet datetime default CURRENT_TIMESTAMP not null,
    hinhanh  varchar(200)                       null
);

INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (1, 'Lòng mẹ', 'Lòng mẹ', 'Và mẹ ơi đừng khóc nhé! Cả đời này mẹ đã khóc nhiều lắm rồi, hãy cười lên vì con đã trưởng thành! Con sẽ lại về dậy sớm nấu cơm cho mẹ, nấu nước cho mẹ tắm như ngày xưa. “Dù cho vai nắng nhưng lòng thương chẳng nhạt màu, vẫn mơ quay về vui vầy dưới bóng mẹ yêu”', null, '2012-07-23 00:00:00', './images/songs/longme.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (2, 'Cảm ơn em đã rời xa anh', 'Vết mưa', 'Cảm ơn em đã cho anh những tháng ngày hạnh phúc, cho anh biết yêu và được yêu. Em cho anh được nếm trải hương vị ngọt ngào của tình yêu nhưng cũng đầy đau khổ và nước mắt. Những tháng ngày đó có lẽ suốt cuộc đời anh không bao giờ quên', null, '2012-02-12 00:00:00', './images/songs/vetmua.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (3, 'Cuộc đời có mấy ngày mai?', 'Phôi pha', 'Đêm nay, trời quang mây tạnh, trong người nghe hoang vắng và tôi ngồi đây “Ôm lòng đêm, Nhìn vầng trăng mới về” mà ngậm ngùi “Nhớ chân giang hồ. Ôi phù du, từng tuổi xuân đã già”', null, '2014-03-13 00:00:00', './images/songs/phoipha.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (4, 'Quê tôi!', 'Quê hương', 'Quê hương là gì mà chở đầy kí ức nhỏ xinh. Có đám trẻ nô đùa bên nhau dưới gốc ổi nhà bà Năm giữa trưa nắng gắt chỉ để chờ bà đi vắng là hái trộm. Có hai anh em tôi bì bõm lội sình bắt cua đem về nhà cho mẹ nấu canh, nấu cháo… Có ba chị em tôi lục đục tự nấu ăn khi mẹ vắng nhà. Có anh tôi luôn dắt tôi đi cùng đường ngõ xóm chỉ để em được vui. Có cả những trận cãi nhau nảy lửa của ba anh em nữa…', null, '2014-02-20 00:00:00', './images/songs/quehuong.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (5, 'Đất nước', 'Đất nước', 'Đã bao nhiêu lần tôi tự hỏi: liệu trên Thế giới này có nơi nào chiến tranh tang thương mà lại rất đổi anh hùng như nước mình không? Liệu có mảnh đất nào mà mỗi tấc đất hôm nay đã thấm máu xương của những thế hệ đi trước nhiều như nước mình không? Và, liệu có một đất nước nào lại có nhiều bà mẹ đau khổ nhưng cũng hết sức gan góc như đất nước mình không?', null, '2010-05-25 00:00:00', './images/songs/datnuoc.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (6, 'Hard Rock Hallelujah', 'Hard Rock Hallelujah', 'Những linh hồn đang lạc lối, mù quáng mất phương hướng trong cõi trần gian đầy nghiệt ngã hãy nên lắng nghe "Hard Rock Hallelujah" để có thể quên tất cả mọi thứ để tìm về đúng bản chất sâu thẳm nhất trong tâm hồn chính mình!', null, '2013-09-12 00:00:00', './images/songs/hardrock.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (7, 'The Unforgiven', 'The Unforgiven', 'Lâu lắm rồi mới nghe lại The Unforgiven II, vì bài này không phải là bài mà tôi thích. Anh bạn tôi lúc trước, đi đâu cũng nghêu ngao bài này ấy, chỉ tại vì hắn đang... thất tình mà lị. Mà sao Metallica có The Unforgiven rồi lại có thêm bài này chi nữa vậy không biết nữa, làm cho tôi cảm thấy hình như hơi bị đúng so với tâm trạng của tôi lúc này.', null, '2010-05-25 00:00:00', './images/songs/TheUnforgiven.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (8, 'Nơi tình yêu bắt đầu', 'Nơi tình yêu bắt đầu', 'Nhiều người sẽ nghĩ làm gì có yêu nhất và làm gì có yêu mãi. Ừ! Chẳng có gì là mãi mãi cả, vì chúng ta không trường tồn vĩnh cửu', 'vai lon', '2014-02-03 00:00:00', './images/songs/noitinhyeubatdau.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (9, 'Love Me Like There’s No Tomorrow', 'Love Me Like There’s No Tomorrow', 'Nếu ai đã từng yêu Queen, yêu cái chất giọng cao, sắc sảo như một vết cắt thật ngọt ẩn giấu bao cảm xúc mãnh liệt của Freddie chắc không thể không "điêu đứng" mỗi khi nghe Love Me Like There’s No Tomorrow.', null, '2013-02-26 00:00:00', './images/songs/loveme.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (10, 'I''m stronger', 'I''m stronger', 'Em không phải là người giỏi giấu cảm xúc, nhưng em lại là người giỏi đoán biết cảm xúc của người khác vậy nên đừng cố nói nhớ em, rằng mọi thứ chỉ là do hoàn cảnh. Và cũng đừng dối em rằng anh đã từng yêu em. Em nhắm mắt cũng cảm nhận được mà, thật đấy', null, '2013-08-21 00:00:00', './images/songs/stronger.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (11, 'Ôi Cuộc Sống Mến Thương', 'Ôi Cuộc Sống Mến Thương', 'Có một câu nói như thế này "Âm nhạc là một cái gì khác lạ mà hầu như tôi muốn nói nó là một phép thần diệu.Vì nó đứng giữa tư tưởng và hiện tượng, tinh thần và vật chất, mọi thứ trung gian mơ hồ thế đó mà không là thế đó giữa các sự vật mà âm nhạc hòa giải"', null, '2011-10-09 00:00:00', './images/songs/csmt.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (12, 'Cây và gió', 'Cây và gió', 'Em và anh, hai đứa quen nhau thật tình cờ. Lời hát của anh từ bài hát “Cây và gió” đã làm tâm hồn em xao động. Nhưng sự thật phũ phàng rằng em chưa bao giờ nói cho anh biết những suy nghĩ tận sâu trong tim mình. Bởi vì em nhút nhát, em không dám đối mặt với thực tế khắc nghiệt, hay thực ra em không dám đối diện với chính mình.', null, '2013-12-05 00:00:00', './images/songs/cayvagio.jpg');
INSERT INTO btth01_cse485.baiviet (ma_bviet, tieude, ten_bhat, tomtat, noidung, ngayviet, hinhanh) VALUES (13, 'Như một cách tạ ơn đời', 'Người thầy', 'Ánh nắng cuối ngày rồi cũng sẽ tắt, dòng sông con đò rồi cũng sẽ rẽ sang một hướng khác. Nhưng việc trồng người luôn cảm thụ với chuyến đò ngang, cứ tần tảo đưa rồi lặng lẽ quay về đưa sang. Con đò năm xưa của Thầy nặng trĩu yêu thương, hy sinh thầm lặng.', null, '2014-01-02 00:00:00', './images/songs/nguoithay.jpg');